### ISSUE TITLE
Add wiktionary as babylon/ dict files.

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-tamil#1]
Users have loved our stardict dicionary distribution setup, and there is demand for tamiL dictionaries:
![image](https://cloud.githubusercontent.com/assets/2664797/23323677/7c5d43b6-fa9e-11e6-995e-315d8b5ec47b.png)

shrI @damooo is skilled at converting wiktionaries to babylon dictionaries (as he has shown with the kannada and telugu repositories). @damooo  - would you be interested in repeating this for tamiL?

**Comment by damooo** [comment]
will do. And a tamil dictionary is avialable at chicago university website, and a dravidian etymology dictionary too. already scraped them. and will soon push all together.

**Comment by vvasuki** [comment]
You mean that you've successfully scraped http://dsal.uchicago.edu/dictionaries/list.html ? That's wonderful news, @damooo  - they have so many dictionaries whose sources they unfortunately do not make available.

**Comment by damooo** [comment]
Haa. that website only.

**Comment by damooo** [comment]
addition of wiktionary may take a week, as i didn't understand it's structure well, and cannot understand tamil.  chicago dictionaries may be will get done before this wiktionary.

**Comment by damooo** [comment]
Anna,
two en-ta dictionaries added.
one is http://www.tamilvu.org/library/pmdictionary/html/madsind.htm from university of madras.
and other is pals, by decompiling this, http://ildc.in/Tamil/GIST/Palaniappa/Pals-Tamil-e-Dictionary.zip . i don't know licencing terms regding this

**Comment by vvasuki** [comment]
Thanks, @damooo - published the tars and set them up to be picked up.
